// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtIzmt-ktVRJsvp1tkWRmri5sDq1-XKw4',
    appId: '1:482094822759:web:YOUR_WEB_APP_ID',
    messagingSenderId: '482094822759',
    projectId: 'hourandmorechatapp',
    authDomain: 'hourandmorechatapp.firebaseapp.com',
    storageBucket: 'hourandmorechatapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtIzmt-ktVRJsvp1tkWRmri5sDq1-XKw4',
    appId: '1:482094822759:android:042a492e70600e74f02bc2',
    messagingSenderId: '482094822759',
    projectId: 'hourandmorechatapp',
    storageBucket: 'hourandmorechatapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtIzmt-ktVRJsvp1tkWRmri5sDq1-XKw4',
    appId: '1:482094822759:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '482094822759',
    projectId: 'hourandmorechatapp',
    storageBucket: 'hourandmorechatapp.firebasestorage.app',
    iosBundleId: 'com.example.hourandmoreflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtIzmt-ktVRJsvp1tkWRmri5sDq1-XKw4',
    appId: '1:482094822759:macos:YOUR_MACOS_APP_ID',
    messagingSenderId: '482094822759',
    projectId: 'hourandmorechatapp',
    storageBucket: 'hourandmorechatapp.firebasestorage.app',
    iosBundleId: 'com.example.hourandmoreflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtIzmt-ktVRJsvp1tkWRmri5sDq1-XKw4',
    appId: '1:482094822759:windows:YOUR_WINDOWS_APP_ID',
    messagingSenderId: '482094822759',
    projectId: 'hourandmorechatapp',
    authDomain: 'hourandmorechatapp.firebaseapp.com',
    storageBucket: 'hourandmorechatapp.firebasestorage.app',
  );
}
